telegram:
    bot:
        username:
        token:
        password:
twitter:
    consumerKey:
        public:
        secret:
    accessToken:
        public:
        secret:
files:
    directory: /home/twitter-bot/files